<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <Authors>Vortex</Authors>
        <Version>1.9.0</Version>
        <PackageProjectUrl>https://github.com/realloon/rimdex</PackageProjectUrl>
        <OutputType>Exe</OutputType>
        <TargetFramework>net10.0</TargetFramework>
        <LangVersion>14</LangVersion>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
        <PublishAot>true</PublishAot>
        <InvariantGlobalization>true</InvariantGlobalization>
        <DebugType>none</DebugType>
        <DebugSymbols>false</DebugSymbols>
        <AllowUnsafeBlocks>true</AllowUnsafeBlocks>
    </PropertyGroup>

    <ItemGroup>
        <PackageReference Include="System.CommandLine" Version="2.0.9" />
        <PackageReference Include="Microsoft.Data.Sqlite.Core" Version="10.0.9" />
        <PackageReference Include="SQLitePCLRaw.provider.e_sqlite3" Version="3.0.3" />
    </ItemGroup>

    <PropertyGroup>
        <SqliteVersion>3530100</SqliteVersion>
        <SqliteUrl>https://sqlite.org/2026/sqlite-amalgamation-$(SqliteVersion).zip</SqliteUrl>
        <SqliteZipFile>$([System.IO.Path]::GetFileName('$(SqliteUrl)'))</SqliteZipFile>
        <SqliteZipPath>$([System.IO.Path]::Combine($(BaseIntermediateOutputPath),$(SqliteZipFile)))</SqliteZipPath>
        <SqliteSrcDirectory>$([System.IO.Path]::Combine($(BaseIntermediateOutputPath),$(SqliteZipFile.Split('.')[0])))</SqliteSrcDirectory>
        <SqliteVecVersion>0.1.9</SqliteVecVersion>
        <SqliteVecUrl>https://github.com/asg017/sqlite-vec/releases/download/v$(SqliteVecVersion)/sqlite-vec-$(SqliteVecVersion)-amalgamation.zip</SqliteVecUrl>
        <SqliteVecZipFile>$([System.IO.Path]::GetFileName('$(SqliteVecUrl)'))</SqliteVecZipFile>
        <SqliteVecZipPath>$([System.IO.Path]::Combine($(BaseIntermediateOutputPath),$(SqliteVecZipFile)))</SqliteVecZipPath>
        <SqliteVecSrcDirectory>$([System.IO.Path]::Combine($(BaseIntermediateOutputPath),'sqlite-vec-$(SqliteVecVersion)'))</SqliteVecSrcDirectory>
        <SqliteVecSourceFile>$([System.IO.Path]::Combine($(SqliteVecSrcDirectory),'sqlite-vec.c'))</SqliteVecSourceFile>
        <SqliteNativeLibrary Condition="'$(OS)' == 'Windows_NT'">$([System.IO.Path]::Combine($(BaseIntermediateOutputPath),'libsqlite3-rimdex.lib'))</SqliteNativeLibrary>
        <SqliteNativeLibrary Condition="'$(OS)' != 'Windows_NT'">$([System.IO.Path]::Combine($(BaseIntermediateOutputPath),'libsqlite3-rimdex.a'))</SqliteNativeLibrary>
    </PropertyGroup>

    <Target Name="BuildSqlite" BeforeTargets="LinkNative" Condition="!Exists($(SqliteNativeLibrary))">
        <DownloadFile SourceUrl="$(SqliteUrl)" DestinationFolder="$(BaseIntermediateOutputPath)" Condition="!Exists($(SqliteZipPath))" />
        <Unzip SourceFiles="$(SqliteZipPath)" DestinationFolder="$(BaseIntermediateOutputPath)" Condition="!Exists($(SqliteSrcDirectory))" />
        <DownloadFile SourceUrl="$(SqliteVecUrl)" DestinationFolder="$(BaseIntermediateOutputPath)" Condition="!Exists($(SqliteVecZipPath))" />
        <MakeDir Directories="$(SqliteVecSrcDirectory)" Condition="!Exists($(SqliteVecSrcDirectory))" />
        <Unzip SourceFiles="$(SqliteVecZipPath)" DestinationFolder="$(SqliteVecSrcDirectory)" Condition="!Exists($(SqliteVecSourceFile))" />
        <Exec Command="cl /nologo /O2 /w /c /I $(SqliteSrcDirectory) /I $(SqliteVecSrcDirectory) $(MSBuildThisFileDirectory)Native\rimdex_sqlite.c /Fo$(BaseIntermediateOutputPath)rimdex_sqlite.obj" Condition="'$(OS)' == 'Windows_NT'" />
        <Exec Command="lib /nologo /out:$(SqliteNativeLibrary) $(BaseIntermediateOutputPath)rimdex_sqlite.obj" Condition="'$(OS)' == 'Windows_NT'" />
        <Exec Command="clang -w -O2 -fPIC -I $(SqliteSrcDirectory) -I $(SqliteVecSrcDirectory) -c $(MSBuildThisFileDirectory)Native/rimdex_sqlite.c -o $(BaseIntermediateOutputPath)rimdex_sqlite.o" Condition="'$(OS)' != 'Windows_NT'" />
        <Exec Command="ar rcs $(SqliteNativeLibrary) $(BaseIntermediateOutputPath)rimdex_sqlite.o" Condition="'$(OS)' != 'Windows_NT'" />
    </Target>

    <ItemGroup>
        <DirectPInvoke Include="e_sqlite3" Visible="false" />
        <NativeLibrary Include="$(SqliteNativeLibrary)" Visible="false" />
    </ItemGroup>

</Project>